name: Release on Deploy
on: release

jobs:
  build:
    strategy:
      matrix:
        os:
          - {prettyName: Windows, action-name: windows-latest}
          - {prettyName: Linux, action-name: ubuntu-latest}
    name: Build on ${{ matrix.os.prettyName }}
    runs-on: ${{ matrix.os.action-name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4